model_family: llama2-7b
model_path: "locuslab/tofu_ft_llama2-7b"
from_hf_hub: true
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 1e-5
split: forget10
data_path: locuslab/TOFU
input_type: question
sentence_chunk: -1
retain_strength: 0.0
beta: 0.1
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 10
forget_loss: intervention
non_factual: false
overwrite_dir: false
seed: 42
weight_decay: 0.01
save_dir_root: results
save_dir: ${save_dir_root}/${model_path}/${forget_loss}/${num_epochs}_${lr}_${split}

eval:
  retain_result: null
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 500

  overwrite: true
  use_pretrained: false

  batch_size: 30

teacher:
  N: 20
  counter_fact_prompt: false
  change_name_back: true
  whp_baseline: false
  verbose: true